### ISSUE TITLE
Type Object is not instantiated until there is a value in the attribute it is targeting?

### ISSUE THREAD

**Issue by pboling** [lucascaton/enumerate_it#108]
```
>> Organization.new.org_type_object
=> nil
```
vs
```
>> Organization.new(org_type: "Admin").org_type_object
=> #<OrgTypes::Admin:0x0000000158bf5320>
```
Of course this doesn't work:
```
  associate_values(
    nil => nil,
```
since the object doesn't have a class to be an instance of until there is a value on the attribute, and nil wouldn't reference any class at all.  But I didn't see it mentioned in the README, and it threw me for a minute.

This isn't really a bug.  It is something obvious that wasn't obvious until it hit me.  I'm refactoring legacy code, and adding enumerators, and the old code does many checks of type and status on objects, regardless of whether the values have been set, so the object replacement paradigm breaks down there.  (for example they are checked during the custom validations on the model, which are before create, and possibly without the instance having a value set for anything).

The solution is to defensively code access to the enumeration object, like with `&` or Rails' `try`, etc.

**Comment by lucascaton** [comment]
Hi @pboling. Sorry, I couldn't fully follow what you're trying to achieve.

Could you please send a sample class/AR model, your enumeration class, and what result you're expecting?

**Comment by pboling** [comment]
This isn't a bug really.  It is obvious behavior that I shouldn't have been surprised by.

It might be useful if there was mention of it in the documentation.

I will come up with a simple example.

**Comment by lucascaton** [comment]
I'm closing the issue for now. Let me know if you need help with anything, Peter 🙂
