### ISSUE TITLE
Always order by enumerate values name when using list

### ISSUE THREAD

**Issue by rmonteiro89** [lucascaton/enumerate_it#50]
I have an enumeration class like this:
```ruby
class MyEnumeration < EnumerateIt::Base
  associate_values :b, :a, :c

  sort_by :none
end
```
If I call MyEnumeration.list, it will return ["a", "b", "c"] but I want to receive ["b", "a", "c"]. Is there any way to do that?

**Comment by cassiomarques** [comment]
Currently `sort_by` only applies for calls to `.to_a` and `.to_json`. When calling `.list` the values will always be listed by their "semantic" ordering.

**Comment by lucassch** [comment]
+1

**Comment by rmonteiro89** [comment]
:+1:

**Comment by lucascaton** [comment]
Fixed here: https://github.com/lucascaton/enumerate_it/releases/tag/v1.2.9

**Comment by lucascaton** [comment]
The latest version should fix it: https://github.com/lucascaton/enumerate_it/releases/tag/v1.2.9.

@rmonteiro89 @lucascs could you please test and let me know how it goes?
