### ISSUE TITLE
How to specify custom message for validates_inclusion_of or disable validates_inclusion_of all together?

### ISSUE THREAD

**Issue by thehappycoder** [lucascaton/enumerate_it#55]

**Comment by lucascaton** [comment]
Hi @thehappycoder,

Unfortunately, the gem doesn't support it yet.

Feel free to submit a PR with this change - ideally, it'd be an option passed to this method: https://github.com/lucascaton/enumerate_it/blob/master/lib/enumerate_it/class_methods.rb#L95

Some relevant links:
* http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_inclusion_of
* http://stackoverflow.com/a/4052350/1445184
