### ISSUE TITLE
Deprecation Warning with Rails 5.0.0.beta3

### ISSUE THREAD

**Issue by simaob** [lucascaton/enumerate_it#56]
DEPRECATION WARNING: ActiveRecord::Base.raise_in_transactional_callbacks= is deprecated, has no effect and will be removed without replacement. (called from <top (required)> at (...)/config/initializers/enumerate_it.rb:1)

Content of my enumerate_it.rb:

`ActiveRecord::Base.extend EnumerateIt`

**Comment by cassiomarques** [comment]
@simaob Just tried the following, with a brand new Rails 5 app (using Rails 5.0.0.beta3)

```
irb(main):001:0> require 'enumerate_it/version'
=> true
irb(main):002:0> EnumerateIt::VERSION
=> "1.2.8"
irb(main):003:0> Rails.version
=> "5.0.0.beta3"
irb(main):004:0> ActiveRecord::Base.extend EnumerateIt
=> ActiveRecord::Base
irb(main):005:0>
```
I didn't receive any warning message. What version of EnumerateIt are you using? I also tried to create a model, an enumeration, associate then using `has_enumeration_for` and I didn't get a warning message either.

**Comment by simaob** [comment]
hi @cassiomarques so this is what I have and get:
<img width="1440" alt="screen shot 2016-03-13 at 17 38 04" src="https://cloud.githubusercontent.com/assets/10764/13730260/72a036ee-e942-11e5-84bb-c172a2a726a5.png">

I'm getting the warning in this project: https://github.com/vizzuality/plannr

**Comment by simaob** [comment]
Maybe it's not being thrown because of enumerate_it, but that's the line that seems to be triggering it. Maybe it's unrelated. apologies if that's the case!

**Comment by cassiomarques** [comment]
Is this a brand new project or are you upgrading an existing one? If you're doing the latter then check other gems you're using. Maybe try disabling gems one by one and trying to reproduce the problem. Let me know how it goes!

**Comment by lucascaton** [comment]
Hi @simaob, I couldn't reproduce the issue either.
Please ensure you're using version `1.2.8` or higher and also Rails `5.0.0.beta3` (or higher).

**Comment by simaob** [comment]
Hi guys, maybe I got it wrong. I've now tried commenting enumerate_it from the Gemfile and I still get the warning, so it's probably not related with your gem. I was mislead by the error message. Sorry about that!
Thanks for your quick replies and well done with this gem!
