### ISSUE TITLE
Set a value to always be at the end of sorted list

### ISSUE THREAD

**Issue by dfmoreto** [lucascaton/enumerate_it#60]
Sometimes, we need to keep a value at the end of a sorted list regardless its value.
For example, I have a list of movie types like ['comedy', 'romance', 'thiller', 'other'] and I need to keep the value 'other' always at the end even if I sort.

**Comment by lucascaton** [comment]
Hi @dfmoreto,

You can solve this using the following code:

```ruby
class MovieType < EnumerateIt::Base
  associate_values(
    :comedy,
    :romance,
    :thiller,
    :other,
    :zzz
  )

  sort_by :none

  class << self
    alias original_list list

    def list
      original_list - [MovieType::OTHER] + [MovieType::OTHER]
    end
  end
end
```

```ruby
MovieType.original_list
# [
#   "comedy",
#   "romance",
#   "thiller",
#   "other",
#   "zzz"
# ]
```

```ruby
MovieType.list
# [
#   "comedy",
#   "romance",
#   "thiller",
#   "zzz",
#   "other"
# ]
```

**Comment by dfmoreto** [comment]
Thanks a lot, @lucascaton !! :smile:
So, before your answer, I forked and worked on a solution in the gem itself. It's working for me, but I'm having some problems when I try to execute RSpec. If you can help me with this, I can commit it.
