### ISSUE TITLE
Symbols for enumeration with spaces

### ISSUE THREAD

**Issue by Bialogs** [lucascaton/enumerate_it#75]
In `enumerations/status.rb`

```ruby
class Status < EnumerateIt::Base
  associate_values(
    :busy,
    :away,
    :'out of office',
    :'in a meeting'
    ...
end
```

Will error with `NameError:  wrong constant name OUT OF OFFICE`, `NameError:  wrong constant name IN A MEETING` etc.

Workaround involves using a hash instead of an array:

```ruby
class Status < EnumerateIt::Base
  associate_values(
    busy: 'busy',
    away: 'away',
    out_of_office: 'out of office',
    in_a_meeting: 'in a meeting'
    ...
end
```

I have a patch I can submit for which should allow the use of symbols with spaces in it if you're interested. The patch involves removing spaces before the call to `const_set` in [`base.rb`](https://github.com/lucascaton/enumerate_it/blob/master/lib/enumerate_it/base.rb#L119).

I also wanted to provide this solution to others as well.

**Comment by lucascaton** [comment]
Hey @Bialogs - thanks for opening this issue.

I think it makes sense, as symbols with spaces are still valid symbols!
Please submit the patch you mentioned 😄

Thank you!
