### ISSUE TITLE
List values of the enumeration

### ISSUE THREAD

**Issue by fidalgo** [lucascaton/enumerate_it#77]
Hi first of all thanks for your work! :clap: 

Would make sense to have a method that would return an array of values, just like we have for the keys?

I've found it useful in one task and that made me wonder why the method it's not available?

**Comment by lucascaton** [comment]
Hey @fidalgo - this method exists already: it's `list`! 😄

```ruby
class Color < EnumerateIt::Base
  associate_values(
    red:   '#f44336',
    blue:  '#2196f3',
    black: '#000000' 
  )
end

Color.keys # [:red, :blue, :black]
Color.list # ["#f44336", "#2196f3", "#000000"]
```

Hope it helps!
