### ISSUE TITLE
Can enumerate_it be used with postgresql enum types?

### ISSUE THREAD

**Issue by ysf** [lucascaton/enumerate_it#82]
Hi there,

can enumerate_it automagically use postgresql enum types?

Here is a Tutorial with some rails-examples:

https://dev.to/amplifr/postgres-enums-with-rails-4ld0

**Comment by lucascaton** [comment]
Not at the moment, but it'd be something nice to have.

Are you keen to submit a PR?

**Comment by lucascaton** [comment]
@ysf I'm closing this issue because it has not been commented on for a while.
PR is welcome, so please re-open it if you're keen to work on this. Thank you.
