### ISSUE TITLE
Extending existing enumerations

### ISSUE THREAD

**Issue by gduprey** [lucascaton/enumerate_it#83]
Is there a way to have  "base" enumeration and then extend it with another enumeration, adding additional values to the extended enumeration as well as carrying the original/base enumeration values?

Example case:
We might have a tax enumeration like 
```
class Payroll::TaxTableType < EnumerateIt::Case
  associate_values(:futa, :suta, :fica, :medicare, :fit, :sit, :lit)
end
```

We then have a model like "Payroll::TaxTable" that has a table_type field that is connected to that association.  So far, easy!

In some other table, we have the need to reference a specific tax table type OR allow any type.  For example/hypothetically:
```
class Payroll::TaxTableUserType < Payroll:TaxTableType
  associate_values(:any)
end
```
Which would ideally result in a list of values that looked like :any, :futa, :suta, :fica, :medicare, etc

That may be just a long way of asking if there is a way to accomplish this when you want two enumerations but just adds a bit on to another enumeration

**Comment by lucascaton** [comment]
Hi @gduprey.
Sorry about the delay in getting back to you.

I think the following code might help you:

```ruby
class Payroll::TaxTableType < EnumerateIt::Base
  associate_values(:futa, :suta, :fica, :medicare, :fit, :sit, :lit)
end
```

```ruby
class Payroll::TaxTableUserType < EnumerateIt::Base
  associate_values(*Payroll::TaxTableType.keys.push(:any))
end
```

**Comment by gduprey** [comment]
Perfect!  Thanks!!
