### ISSUE TITLE
`has_enumeration_for` with default value

### ISSUE THREAD

**Issue by de-farias** [lucascaton/enumerate_it#95]
Hi there!

Is there a way to set a default value when using an enumeration with an ActiveRecord model (or any other kind of object)?

**Comment by lucascaton** [comment]
Hey @de-farias!

Yes, ActiveRecord has a method called `attribute`, which you can use in your models.
Here's how to do it: https://stackoverflow.com/a/43484863/1445184 🙂

**Comment by de-farias** [comment]
Nice! Thank you!!
