### ISSUE TITLE
Set default options for has_enumeration_for

### ISSUE THREAD

**Issue by KieranP** [lucascaton/enumerate_it#96]
I have several enumerations. I'm setting the following for each of them:

```
create_helpers: { prefix: true },
create_scopes: { prefix: true }
```

Would be nice to be able to set default options, e.g.

```
EnumerateIt.configuration.defaults = {
  create_helpers: { prefix: true },
  create_scopes: { prefix: true }
}
```

**Comment by lucascaton** [comment]
Thanks, @KieranP! That sounds like a nice feature indeed.
Are you keen to submit a PR with that?

**Comment by lucascaton** [comment]
@KieranP?

**Comment by lucascaton** [comment]
Closing this issue since I haven't got any response.
